spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mariadb
        username: mariadb
        password: mariadb
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect